# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

nndm_cpp <- function(X, Gij, phi, min_train) {
    .Call(`_blockCV_nndm_cpp`, X, Gij, phi, min_train)
}

similarity_cpp <- function(train_mat, test_mat, rand_mat, L1 = TRUE) {
    .Call(`_blockCV_similarity_cpp`, train_mat, test_mat, rand_mat, L1)
}

