# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

nndm_cpp <- function(X, Gjstar, Gij, rmin, phi, imin, jmin, min_train) {
    .Call(`_blockCV_nndm_cpp`, X, Gjstar, Gij, rmin, phi, imin, jmin, min_train)
}

